<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>description_on_syllabus</name>
   <tag></tag>
   <elementGuidId>ef24aea6-0b94-4e64-baef-336cdbdf3277</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#lesson_lesson_syllabuses_attributes_1624444098867_description</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@name='lesson[lesson_syllabuses_attributes][1624956855938][description]']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>lesson[lesson_syllabuses_attributes][1624444098867][description]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lesson_lesson_syllabuses_attributes_1624444098867_description</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lesson_lesson_syllabuses_attributes_1624444098867_description&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='lesson_lesson_syllabuses_attributes_1624444098867_description']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='new_lesson']/div/div[7]/div[2]/div/div/div/div/div/div/div[2]/div[2]/textarea</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/textarea</value>
   </webElementXpaths>
</WebElementEntity>
