<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>subscription-trial</name>
   <tag></tag>
   <elementGuidId>5a0b292c-468c-4e18-9926-d4376f250b6d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.option.active</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@data-value='trial']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>option active</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-value</name>
      <type>Main</type>
      <value>trial</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>trial</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;edit_user_220&quot;)/div[@class=&quot;vybe-form-container no-padding-horizontal&quot;]/div[@class=&quot;card-section&quot;]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-3 pl-0 for-select no-wrapper&quot;]/div[@class=&quot;field-unit field-unit--select&quot;]/div[@class=&quot;field-unit__field&quot;]/div[@class=&quot;selectize-control single&quot;]/div[@class=&quot;selectize-dropdown single&quot;]/div[@class=&quot;selectize-dropdown-content&quot;]/div[@class=&quot;option active&quot;]</value>
   </webElementProperties>
</WebElementEntity>
